#idrac_network_excel.yml
---
- name: Set iDrac network address
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    search_range:
      start_col: 1
      end_col: 6
      start_row: 2

  vars_files: ../../../vars/passwords.yml

  tasks:
    - name: Retrive iDrac Data
      open_excel:
        src: ../../../files/project_configuration_sample.xlsx
        sheet_name: iDrac_Basic
        op: "r"
        read_range: "{{ search_range }}"
      register: data
      ignore_errors: true

    - name: setniccfg
      raw: racadm -r "{{ item.tmp_address }}" -u "{{ iDRAC_Username }}" -p "{{ iDRAC_Password }}" Setniccfg -s "{{ item.address }}" "{{ item.subnet }}" "{{ item.gateway }}"
      when: "item.address != 'N/A'"
      loop: "{{ data.sheet_index_0 }}"

    - pause:
        seconds: 20

    - name: Check if changed
      raw: racadm -r "{{ item.address }}" -u "{{ iDRAC_Username }}" -p "{{ iDRAC_Password }}" get iDRAC.ipv4
      when: "item.address != 'N/A'"
      loop: "{{ data.sheet_index_0 }}"
      register: check

    - name: Debug
      debug:
        msg: "{% if item.item.address in item.stdout_lines[7] %} iDrac Network configuration process for idrac ip '{{ item.item.address }}' has been executed Successfully {% else %} iDrac Network configuration process for idrac ip '{{ item.item.address }}' has encountered a problem while executing racadm command. {% endif %}"
      when:
        - "item.item.address != 'N/A'"
        - "check.results != None"
      loop: "{{ check.results }}"
      loop_control:
        label: "{{ item.item.address }}"
