#esxi_raid__excel.yml
---
- name: Set ESXi Raid
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    search_range:
      start_col: 1
      end_col: 5
      start_row: 2

  vars_files: ../../../vars/passwords.yml

  tasks:
    - name: Retrive iDrac Data
      open_excel:
        src: ../../../files/project_configuration_sample.xlsx
        sheet_name: ESXi
        op: "r"
        read_range: "{{ search_range }}"
      register: data
      ignore_errors: true

#    - name: Make sure server is powered off
#      raw: racadm -r "{{ item.address }}" -u "{{ iDRAC_Username }}" -p "{{ iDRAC_Password }}" serveraction powerdown
#      when:
#        - "item.address != 'N/A'"
#      loop: "{{ data.sheet_index_0 }}"
#      ignore_errors: true

    - name: Get all server PDisks
      raw: racadm -r "{{ item.address }}" -u "{{ iDRAC_Username }}" -p "{{ iDRAC_Password }}" storage get pdisks
      when: "item.address != 'N/A'"
      loop: "{{ data.sheet_index_0 }}"
      register: disks

    - name: Get all PDisks names
      debug:
        msg: "{{ item.stdout_lines[6:] }}"
      loop: "{{ disks.results }}"
      loop_control:
        label: ""
      register: disksName

    - debug: var=disksName

    - name: Set first raid from excel file
      raw: racadm -r "{{ item.item.item.address }}" -u "{{ iDRAC_Username }}" -p "{{ iDRAC_Password }}" storage createvd:RAID.Integrated.1-1 -rl "{{ item.item.item.vdisk1 }}" -wp wb -rp ra -name Raid1 -pdkey:"{{ item.item.stdout_lines[:"{{ item.item.item.vdisk1_pdisk_num }}"|int] }}"
      loop: "{{ disksName.results }}" 
      register: err
      ignore_errors: true

    - debug: var=err


